# ============================================
# REPO 1: CODE REPOSITORY - ALL-IN-ONE
# File: cloudbuild.yaml
# ============================================
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/focal-psyche-460009-a5/encodex-yash/$_APP_NAME:$SHORT_SHA'
      - '-f'
      - 'Dockerfile'
      - '.'
    id: 'build-image'
  
  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/focal-psyche-460009-a5/encodex-yash/$_APP_NAME:$SHORT_SHA'
    id: 'push-image'
    waitFor: ['build-image']
  
  # Step 3: Update deployment repo directly
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['GITHUB_TOKEN']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Configure git
        git config --global user.email "cloudbuild@focal-psyche-460009-a5.iam.gserviceaccount.com"
        git config --global user.name "Cloud Build Bot"
        
        # Clone deployment repo
        echo "Cloning deployment repository..."
        git clone https://$$GITHUB_TOKEN@github.com/yash-study/argocd.git deployment-repo
        cd deployment-repo
        
        # Update deployment.yaml
        IMAGE_TAG="$SHORT_SHA"
        IMAGE_NAME="$_APP_NAME"
        IMAGE_REGISTRY="us-central1-docker.pkg.dev/focal-psyche-460009-a5/encodex-yash"
        FULL_IMAGE="$${IMAGE_REGISTRY}/$${IMAGE_NAME}:$${IMAGE_TAG}"
        
        echo "================================================"
        echo "Updating deployment with image: $${FULL_IMAGE}"
        echo "================================================"
        
        if [ -f "apps-of-app-structure/apps/nginx/deployment.yaml" ]; then
          sed -i "s|image:.*$${IMAGE_NAME}:.*|image: $${FULL_IMAGE}|g" apps-of-app-structure/apps/nginx/deployment.yaml
          
          # Show changes
          echo "Changes made:"
          git diff apps-of-app-structure/apps/nginx/deployment.yaml
          
          # Commit and push
          git add apps-of-app-structure/apps/nginx/deployment.yaml
          git commit -m "Deploy ${IMAGE_NAME}:${IMAGE_TAG} - Image: ${FULL_IMAGE} - Build: $BUILD_ID"
          
          git push https://$$GITHUB_TOKEN@github.com/yash-study/argocd.git main
          
          echo "================================================"
          echo "✅ Deployment updated successfully!"
          echo "🎯 ArgoCD will sync these changes"
          echo "================================================"
        else
          echo "❌ Deployment file not found!"
          exit 1
        fi
    id: 'update-deployment'
    waitFor: ['push-image']

# Configure secrets
availableSecrets:
  secretManager:
    - versionName: projects/339960399182/secrets/yash-personal-githubtoken/versions/1
      env: 'GITHUB_TOKEN'

# Images pushed to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/focal-psyche-460009-a5/encodex-yash/$_APP_NAME:$SHORT_SHA'

# Timeout
timeout: '1200s'

# Substitutions
substitutions:
  _APP_NAME: 'nginx'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'